//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom.Compiler;

namespace CloudFoundry.CloudController.V2.Test.Deserialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServiceAuthTokensDeprecatedTest
    {


        [TestMethod]
        public void TestFilterResultSetByLabelDeprecatedResponse()
        {
            string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""79423ad9-d7f3-4694-af71-cd24f03022c3"",
        ""url"": ""/v2/service_auth_tokens/402b0f2a-0c94-416b-81d1-568e81859737"",
        ""created_at"": ""2016-04-28T14:32:10Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""label"": ""Nic-Token"",
        ""provider"": ""provider-7""
      }
    }
  ]
}";

            PagedResponseCollection<FilterResultSetByLabelDeprecatedResponse> page = Utilities.DeserializePage<FilterResultSetByLabelDeprecatedResponse>(json, null);

            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("79423ad9-d7f3-4694-af71-cd24f03022c3", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_auth_tokens/402b0f2a-0c94-416b-81d1-568e81859737", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-28T14:32:10Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("Nic-Token", TestUtil.ToTestableString(page[0].Label), true);
            Assert.AreEqual("provider-7", TestUtil.ToTestableString(page[0].Provider), true);
        }

        [TestMethod]
        public void TestListAllServiceAuthTokensDeprecatedResponse()
        {
            string json = @"{
  ""total_results"": 3,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""d16a8ad8-7ac6-4f32-af13-41ad1a92e171"",
        ""url"": ""/v2/service_auth_tokens/9f20be2c-7b0f-40c2-b8ba-6311172f6643"",
        ""created_at"": ""2016-04-28T14:32:10Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""label"": ""label-14"",
        ""provider"": ""provider-14""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""d16a8ad8-7ac6-4f32-af13-41ad1a92e171"",
        ""url"": ""/v2/service_auth_tokens/12af73ea-6674-443c-bad3-ec190c214bb4"",
        ""created_at"": ""2016-04-28T14:32:10Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""label"": ""label-15"",
        ""provider"": ""provider-15""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""d16a8ad8-7ac6-4f32-af13-41ad1a92e171"",
        ""url"": ""/v2/service_auth_tokens/8ee3345c-86b7-48c7-9c54-780f44b1bcae"",
        ""created_at"": ""2016-04-28T14:32:10Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""label"": ""label-16"",
        ""provider"": ""provider-16""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllServiceAuthTokensDeprecatedResponse> page = Utilities.DeserializePage<ListAllServiceAuthTokensDeprecatedResponse>(json, null);

            Assert.AreEqual("3", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("d16a8ad8-7ac6-4f32-af13-41ad1a92e171", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_auth_tokens/9f20be2c-7b0f-40c2-b8ba-6311172f6643", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-28T14:32:10Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("label-14", TestUtil.ToTestableString(page[0].Label), true);
            Assert.AreEqual("provider-14", TestUtil.ToTestableString(page[0].Provider), true);
            Assert.AreEqual("d16a8ad8-7ac6-4f32-af13-41ad1a92e171", TestUtil.ToTestableString(page[1].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_auth_tokens/12af73ea-6674-443c-bad3-ec190c214bb4", TestUtil.ToTestableString(page[1].EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-28T14:32:10Z", TestUtil.ToTestableString(page[1].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[1].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("label-15", TestUtil.ToTestableString(page[1].Label), true);
            Assert.AreEqual("provider-15", TestUtil.ToTestableString(page[1].Provider), true);
            Assert.AreEqual("d16a8ad8-7ac6-4f32-af13-41ad1a92e171", TestUtil.ToTestableString(page[2].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_auth_tokens/8ee3345c-86b7-48c7-9c54-780f44b1bcae", TestUtil.ToTestableString(page[2].EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-28T14:32:10Z", TestUtil.ToTestableString(page[2].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[2].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("label-16", TestUtil.ToTestableString(page[2].Label), true);
            Assert.AreEqual("provider-16", TestUtil.ToTestableString(page[2].Provider), true);
        }

        [TestMethod]
        public void TestFilterResultSetByProviderDeprecatedResponse()
        {
            string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""092d7bfc-1357-4984-bdda-8b8fb52a9067"",
        ""url"": ""/v2/service_auth_tokens/c0ebc5bf-24c9-418c-8718-e8954931e8a9"",
        ""created_at"": ""2016-04-28T14:32:10Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""label"": ""label-4"",
        ""provider"": ""Face-Offer""
      }
    }
  ]
}";

            PagedResponseCollection<FilterResultSetByProviderDeprecatedResponse> page = Utilities.DeserializePage<FilterResultSetByProviderDeprecatedResponse>(json, null);

            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("092d7bfc-1357-4984-bdda-8b8fb52a9067", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_auth_tokens/c0ebc5bf-24c9-418c-8718-e8954931e8a9", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-28T14:32:10Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("label-4", TestUtil.ToTestableString(page[0].Label), true);
            Assert.AreEqual("Face-Offer", TestUtil.ToTestableString(page[0].Provider), true);
        }

        [TestMethod]
        public void TestRetrieveServiceAuthTokenDeprecatedResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""4fef25da-3424-4ad0-b65b-ee3353effd95"",
    ""url"": ""/v2/service_auth_tokens/4726b31d-2383-426e-9388-e48ae99eba91"",
    ""created_at"": ""2016-04-28T14:32:10Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""label"": ""label-8"",
    ""provider"": ""provider-8""
  }
}";

            RetrieveServiceAuthTokenDeprecatedResponse obj = Utilities.DeserializeJson<RetrieveServiceAuthTokenDeprecatedResponse>(json);

            Assert.AreEqual("4fef25da-3424-4ad0-b65b-ee3353effd95", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_auth_tokens/4726b31d-2383-426e-9388-e48ae99eba91", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-28T14:32:10Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("label-8", TestUtil.ToTestableString(obj.Label), true);
            Assert.AreEqual("provider-8", TestUtil.ToTestableString(obj.Provider), true);
        }
    }
}
