//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom.Compiler;

namespace CloudFoundry.CloudController.V2.Test.Deserialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServiceKeysTest
    {


        [TestMethod]
        public void TestCreateServiceKeyResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""d225e5fb-cee7-4811-8749-564de8285312"",
    ""url"": ""/v2/service_keys/921780f2-93c3-4a07-bb04-01c2edf9ccfc"",
    ""created_at"": ""2016-04-11T13:33:04Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""name-780"",
    ""service_instance_guid"": ""d225e5fb-cee7-4811-8749-564de8285312"",
    ""credentials"": {
      ""creds-key-47"": ""creds-val-47""
    },
    ""service_instance_url"": ""/v2/service_instances/162d8b2f-13bd-45d0-8401-e6aa6902e70b""
  }
}";

            CreateServiceKeyResponse obj = Utilities.DeserializeJson<CreateServiceKeyResponse>(json);

            Assert.AreEqual("d225e5fb-cee7-4811-8749-564de8285312", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_keys/921780f2-93c3-4a07-bb04-01c2edf9ccfc", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-11T13:33:04Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-780", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("d225e5fb-cee7-4811-8749-564de8285312", TestUtil.ToTestableString(obj.ServiceInstanceGuid), true);
            Assert.AreEqual("/v2/service_instances/162d8b2f-13bd-45d0-8401-e6aa6902e70b", TestUtil.ToTestableString(obj.ServiceInstanceUrl), true);
        }

        [TestMethod]
        public void TestListAllServiceKeysResponse()
        {
            string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""e84955b9-714d-4985-9917-15c3dd9ed84a"",
        ""url"": ""/v2/service_keys/8eb568c5-8cf6-4476-98c4-7a8b481d2315"",
        ""created_at"": ""2016-04-11T13:33:04Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-767"",
        ""service_instance_guid"": ""e84955b9-714d-4985-9917-15c3dd9ed84a"",
        ""credentials"": {
          ""creds-key-45"": ""creds-val-45""
        },
        ""service_instance_url"": ""/v2/service_instances/2c2d855a-6604-46e7-a528-63c89dd113a2""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllServiceKeysResponse> page = Utilities.DeserializePage<ListAllServiceKeysResponse>(json, null);

            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("e84955b9-714d-4985-9917-15c3dd9ed84a", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_keys/8eb568c5-8cf6-4476-98c4-7a8b481d2315", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-11T13:33:04Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-767", TestUtil.ToTestableString(page[0].Name), true);
            Assert.AreEqual("e84955b9-714d-4985-9917-15c3dd9ed84a", TestUtil.ToTestableString(page[0].ServiceInstanceGuid), true);
            Assert.AreEqual("/v2/service_instances/2c2d855a-6604-46e7-a528-63c89dd113a2", TestUtil.ToTestableString(page[0].ServiceInstanceUrl), true);
        }

        [TestMethod]
        public void TestRetrieveServiceKeyResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""4732ea93-66db-4650-a15e-6ef64ba258aa"",
    ""url"": ""/v2/service_keys/af523963-9965-4862-9047-e4e63257dd1d"",
    ""created_at"": ""2016-04-11T13:33:04Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""name-793"",
    ""service_instance_guid"": ""4732ea93-66db-4650-a15e-6ef64ba258aa"",
    ""credentials"": {
      ""creds-key-51"": ""creds-val-51""
    },
    ""service_instance_url"": ""/v2/service_instances/0ac1ac69-2520-4a93-bf96-7b90ff80677d""
  }
}";

            RetrieveServiceKeyResponse obj = Utilities.DeserializeJson<RetrieveServiceKeyResponse>(json);

            Assert.AreEqual("4732ea93-66db-4650-a15e-6ef64ba258aa", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_keys/af523963-9965-4862-9047-e4e63257dd1d", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-04-11T13:33:04Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-793", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("4732ea93-66db-4650-a15e-6ef64ba258aa", TestUtil.ToTestableString(obj.ServiceInstanceGuid), true);
            Assert.AreEqual("/v2/service_instances/0ac1ac69-2520-4a93-bf96-7b90ff80677d", TestUtil.ToTestableString(obj.ServiceInstanceUrl), true);
        }
    }
}
