//------------------------------------------------------------------------------
// <auto-generated>
  //     This code was generated by a tool.
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  // </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.QualityTools.Testing.Fakes;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.CodeDom.Compiler;
using System.Net;
using System.Threading.Tasks;

namespace CloudFoundry.CloudController.V2.Client.Test.Fake
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServicePlanVisibilitiesEndpoint
{
        [TestMethod]
        public void UpdateServicePlanVisibilityTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""21f38103-9215-4ab5-9492-e03a8695024c"",
    ""url"": ""/v2/service_plan_visibilities/f107cc17-a9e8-400d-8b69-0f7249479ca5"",
    ""created_at"": ""2016-04-11T13:33:06Z"",
    ""updated_at"": ""2016-04-11T13:33:06Z""
  },
  ""entity"": {
    ""service_plan_guid"": ""21f38103-9215-4ab5-9492-e03a8695024c"",
    ""organization_guid"": ""21f38103-9215-4ab5-9492-e03a8695024c"",
    ""service_plan_url"": ""/v2/service_plans/9cce17e7-ed45-44ac-a17a-c49e6edafc59"",
    ""organization_url"": ""/v2/organizations/3c8e3eb7-b543-4206-9225-077b7c74467a""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)201;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();

                UpdateServicePlanVisibilityRequest value = new UpdateServicePlanVisibilityRequest();


                var obj = cfClient.ServicePlanVisibilities.UpdateServicePlanVisibility(guid, value).Result;


                Assert.AreEqual("21f38103-9215-4ab5-9492-e03a8695024c", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_plan_visibilities/f107cc17-a9e8-400d-8b69-0f7249479ca5", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-04-11T13:33:06Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("2016-04-11T13:33:06Z", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("21f38103-9215-4ab5-9492-e03a8695024c", TestUtil.ToTestableString(obj.ServicePlanGuid), true);
                Assert.AreEqual("21f38103-9215-4ab5-9492-e03a8695024c", TestUtil.ToTestableString(obj.OrganizationGuid), true);
                Assert.AreEqual("/v2/service_plans/9cce17e7-ed45-44ac-a17a-c49e6edafc59", TestUtil.ToTestableString(obj.ServicePlanUrl), true);
                Assert.AreEqual("/v2/organizations/3c8e3eb7-b543-4206-9225-077b7c74467a", TestUtil.ToTestableString(obj.OrganizationUrl), true);

            }
        }

        [TestMethod]
        public void DeleteServicePlanVisibilitiesTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                clients.ExpectedStatusCode = (HttpStatusCode)204;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                cfClient.ServicePlanVisibilities.DeleteServicePlanVisibilities(guid).Wait();

            }
        }

        [TestMethod]
        public void CreateServicePlanVisibilityTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""cbd98206-6039-45b5-84ec-2ebb18e93b1a"",
    ""url"": ""/v2/service_plan_visibilities/94337fa3-7c57-4e20-8c41-23752d6654c3"",
    ""created_at"": ""2016-04-11T13:33:06Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""service_plan_guid"": ""cbd98206-6039-45b5-84ec-2ebb18e93b1a"",
    ""organization_guid"": ""cbd98206-6039-45b5-84ec-2ebb18e93b1a"",
    ""service_plan_url"": ""/v2/service_plans/458a821b-0440-4e0b-805d-ad5d5b186c32"",
    ""organization_url"": ""/v2/organizations/1d5bdbb5-9bdf-45b9-ab5a-e719ae7521ca""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)201;
                var cfClient = clients.CreateCloudFoundryClient();

                CreateServicePlanVisibilityRequest value = new CreateServicePlanVisibilityRequest();


                var obj = cfClient.ServicePlanVisibilities.CreateServicePlanVisibility(value).Result;


                Assert.AreEqual("cbd98206-6039-45b5-84ec-2ebb18e93b1a", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_plan_visibilities/94337fa3-7c57-4e20-8c41-23752d6654c3", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-04-11T13:33:06Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("cbd98206-6039-45b5-84ec-2ebb18e93b1a", TestUtil.ToTestableString(obj.ServicePlanGuid), true);
                Assert.AreEqual("cbd98206-6039-45b5-84ec-2ebb18e93b1a", TestUtil.ToTestableString(obj.OrganizationGuid), true);
                Assert.AreEqual("/v2/service_plans/458a821b-0440-4e0b-805d-ad5d5b186c32", TestUtil.ToTestableString(obj.ServicePlanUrl), true);
                Assert.AreEqual("/v2/organizations/1d5bdbb5-9bdf-45b9-ab5a-e719ae7521ca", TestUtil.ToTestableString(obj.OrganizationUrl), true);

            }
        }

        [TestMethod]
        public void RetrieveServicePlanVisibilityTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""d98d55ff-732a-4e94-9fd2-b254200bc9ba"",
    ""url"": ""/v2/service_plan_visibilities/a8ddb4e6-bb69-42a7-b8a9-94279b808eb5"",
    ""created_at"": ""2016-04-11T13:33:06Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""service_plan_guid"": ""d98d55ff-732a-4e94-9fd2-b254200bc9ba"",
    ""organization_guid"": ""d98d55ff-732a-4e94-9fd2-b254200bc9ba"",
    ""service_plan_url"": ""/v2/service_plans/eb685123-b2d8-41e0-a065-c428d98eedf6"",
    ""organization_url"": ""/v2/organizations/e4de366c-a0b8-490a-9fbd-48c045b39f08""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                var obj = cfClient.ServicePlanVisibilities.RetrieveServicePlanVisibility(guid).Result;


                Assert.AreEqual("d98d55ff-732a-4e94-9fd2-b254200bc9ba", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_plan_visibilities/a8ddb4e6-bb69-42a7-b8a9-94279b808eb5", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-04-11T13:33:06Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("d98d55ff-732a-4e94-9fd2-b254200bc9ba", TestUtil.ToTestableString(obj.ServicePlanGuid), true);
                Assert.AreEqual("d98d55ff-732a-4e94-9fd2-b254200bc9ba", TestUtil.ToTestableString(obj.OrganizationGuid), true);
                Assert.AreEqual("/v2/service_plans/eb685123-b2d8-41e0-a065-c428d98eedf6", TestUtil.ToTestableString(obj.ServicePlanUrl), true);
                Assert.AreEqual("/v2/organizations/e4de366c-a0b8-490a-9fbd-48c045b39f08", TestUtil.ToTestableString(obj.OrganizationUrl), true);

            }
        }

        [TestMethod]
        public void ListAllServicePlanVisibilitiesTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""3523bc45-ec56-4532-8c67-56e4d14a5405"",
        ""url"": ""/v2/service_plan_visibilities/99aa6d39-daa4-434e-9754-274dba5b4be1"",
        ""created_at"": ""2016-04-11T13:33:07Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""service_plan_guid"": ""3523bc45-ec56-4532-8c67-56e4d14a5405"",
        ""organization_guid"": ""3523bc45-ec56-4532-8c67-56e4d14a5405"",
        ""service_plan_url"": ""/v2/service_plans/ddd42762-86de-470e-a4e8-09efa3a4b374"",
        ""organization_url"": ""/v2/organizations/e5ada373-229f-4045-947b-3991300797f1""
      }
    }
  ]
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();


                var obj = cfClient.ServicePlanVisibilities.ListAllServicePlanVisibilities().Result;

                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalResults), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalPages), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.PreviousUrl), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.NextUrl), true);
                Assert.AreEqual("3523bc45-ec56-4532-8c67-56e4d14a5405", TestUtil.ToTestableString(obj[0].EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_plan_visibilities/99aa6d39-daa4-434e-9754-274dba5b4be1", TestUtil.ToTestableString(obj[0].EntityMetadata.Url), true);
                Assert.AreEqual("2016-04-11T13:33:07Z", TestUtil.ToTestableString(obj[0].EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("3523bc45-ec56-4532-8c67-56e4d14a5405", TestUtil.ToTestableString(obj[0].ServicePlanGuid), true);
                Assert.AreEqual("3523bc45-ec56-4532-8c67-56e4d14a5405", TestUtil.ToTestableString(obj[0].OrganizationGuid), true);
                Assert.AreEqual("/v2/service_plans/ddd42762-86de-470e-a4e8-09efa3a4b374", TestUtil.ToTestableString(obj[0].ServicePlanUrl), true);
                Assert.AreEqual("/v2/organizations/e5ada373-229f-4045-947b-3991300797f1", TestUtil.ToTestableString(obj[0].OrganizationUrl), true);

            }
        }

    }
}