//------------------------------------------------------------------------------
// <auto-generated>
  //     This code was generated by a tool.
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  // </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.QualityTools.Testing.Fakes;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.CodeDom.Compiler;
using System.Net;
using System.Threading.Tasks;

namespace CloudFoundry.CloudController.V2.Client.Test.Fake
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class AppUsageEventsEndpoint
{
        [TestMethod]
        public void RetrieveAppUsageEventTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""e543f9ba-59f0-4ea6-85ae-078a66a56b5a"",
    ""url"": ""/v2/app_usage_events/7f5070de-df81-4969-a414-9ff55a0636d4"",
    ""created_at"": ""2016-04-11T13:32:47Z""
  },
  ""entity"": {
    ""state"": ""STARTED"",
    ""previous_state"": null,
    ""memory_in_mb_per_instance"": 564,
    ""previous_memory_in_mb_per_instance"": null,
    ""instance_count"": 1,
    ""previous_instance_count"": null,
    ""app_guid"": ""e543f9ba-59f0-4ea6-85ae-078a66a56b5a"",
    ""app_name"": ""name-291"",
    ""space_guid"": ""e543f9ba-59f0-4ea6-85ae-078a66a56b5a"",
    ""space_name"": ""name-292"",
    ""org_guid"": ""e543f9ba-59f0-4ea6-85ae-078a66a56b5a"",
    ""buildpack_guid"": ""e543f9ba-59f0-4ea6-85ae-078a66a56b5a"",
    ""buildpack_name"": ""name-293"",
    ""package_state"": ""STAGED"",
    ""previous_package_state"": null,
    ""parent_app_guid"": null,
    ""parent_app_name"": null,
    ""process_type"": ""web"",
    ""task_name"": null,
    ""task_guid"": null
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                var obj = cfClient.AppUsageEvents.RetrieveAppUsageEvent(guid).Result;


                Assert.AreEqual("e543f9ba-59f0-4ea6-85ae-078a66a56b5a", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/app_usage_events/7f5070de-df81-4969-a414-9ff55a0636d4", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-04-11T13:32:47Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("STARTED", TestUtil.ToTestableString(obj.State), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.PreviousState), true);
                Assert.AreEqual("564", TestUtil.ToTestableString(obj.MemoryInMbPerInstance), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.PreviousMemoryInMbPerInstance), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj.InstanceCount), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.PreviousInstanceCount), true);
                Assert.AreEqual("e543f9ba-59f0-4ea6-85ae-078a66a56b5a", TestUtil.ToTestableString(obj.AppGuid), true);
                Assert.AreEqual("name-291", TestUtil.ToTestableString(obj.AppName), true);
                Assert.AreEqual("e543f9ba-59f0-4ea6-85ae-078a66a56b5a", TestUtil.ToTestableString(obj.SpaceGuid), true);
                Assert.AreEqual("name-292", TestUtil.ToTestableString(obj.SpaceName), true);
                Assert.AreEqual("e543f9ba-59f0-4ea6-85ae-078a66a56b5a", TestUtil.ToTestableString(obj.OrgGuid), true);
                Assert.AreEqual("e543f9ba-59f0-4ea6-85ae-078a66a56b5a", TestUtil.ToTestableString(obj.BuildpackGuid), true);
                Assert.AreEqual("name-293", TestUtil.ToTestableString(obj.BuildpackName), true);
                Assert.AreEqual("STAGED", TestUtil.ToTestableString(obj.PackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.PreviousPackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.ParentAppGuid), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.ParentAppName), true);
                Assert.AreEqual("web", TestUtil.ToTestableString(obj.ProcessType), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.TaskName), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.TaskGuid), true);

            }
        }

        [TestMethod]
        public void PurgeAndReseedAppUsageEventsTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                clients.ExpectedStatusCode = (HttpStatusCode)204;
                var cfClient = clients.CreateCloudFoundryClient();


                cfClient.AppUsageEvents.PurgeAndReseedAppUsageEvents().Wait();

            }
        }

        [TestMethod]
        public void ListAllAppUsageEventsTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""total_results"": 2,
  ""total_pages"": 2,
  ""prev_url"": null,
  ""next_url"": ""/v2/app_usage_events?after_guid=81b51bbe-7261-483e-a4fd-cbd77264c4f6=asc=2=1"",
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""bc51034d-267d-4a39-a384-78196b0bc300"",
        ""url"": ""/v2/app_usage_events/88911495-abe0-42c1-8c0e-add22bb24ded"",
        ""created_at"": ""2016-04-11T13:32:47Z""
      },
      ""entity"": {
        ""state"": ""STARTED"",
        ""previous_state"": null,
        ""memory_in_mb_per_instance"": 564,
        ""previous_memory_in_mb_per_instance"": null,
        ""instance_count"": 1,
        ""previous_instance_count"": null,
        ""app_guid"": ""bc51034d-267d-4a39-a384-78196b0bc300"",
        ""app_name"": ""name-303"",
        ""space_guid"": ""bc51034d-267d-4a39-a384-78196b0bc300"",
        ""space_name"": ""name-304"",
        ""org_guid"": ""bc51034d-267d-4a39-a384-78196b0bc300"",
        ""buildpack_guid"": ""bc51034d-267d-4a39-a384-78196b0bc300"",
        ""buildpack_name"": ""name-305"",
        ""package_state"": ""STAGED"",
        ""previous_package_state"": null,
        ""parent_app_guid"": null,
        ""parent_app_name"": null,
        ""process_type"": ""web"",
        ""task_name"": null,
        ""task_guid"": null
      }
    }
  ]
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();


                var obj = cfClient.AppUsageEvents.ListAllAppUsageEvents().Result;

                Assert.AreEqual("2", TestUtil.ToTestableString(obj.Properties.TotalResults), true);
                Assert.AreEqual("2", TestUtil.ToTestableString(obj.Properties.TotalPages), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.PreviousUrl), true);
                Assert.AreEqual("/v2/app_usage_events?after_guid=81b51bbe-7261-483e-a4fd-cbd77264c4f6=asc=2=1", TestUtil.ToTestableString(obj.Properties.NextUrl), true);
                Assert.AreEqual("bc51034d-267d-4a39-a384-78196b0bc300", TestUtil.ToTestableString(obj[0].EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/app_usage_events/88911495-abe0-42c1-8c0e-add22bb24ded", TestUtil.ToTestableString(obj[0].EntityMetadata.Url), true);
                Assert.AreEqual("2016-04-11T13:32:47Z", TestUtil.ToTestableString(obj[0].EntityMetadata.CreatedAt), true);
                Assert.AreEqual("STARTED", TestUtil.ToTestableString(obj[0].State), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].PreviousState), true);
                Assert.AreEqual("564", TestUtil.ToTestableString(obj[0].MemoryInMbPerInstance), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].PreviousMemoryInMbPerInstance), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj[0].InstanceCount), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].PreviousInstanceCount), true);
                Assert.AreEqual("bc51034d-267d-4a39-a384-78196b0bc300", TestUtil.ToTestableString(obj[0].AppGuid), true);
                Assert.AreEqual("name-303", TestUtil.ToTestableString(obj[0].AppName), true);
                Assert.AreEqual("bc51034d-267d-4a39-a384-78196b0bc300", TestUtil.ToTestableString(obj[0].SpaceGuid), true);
                Assert.AreEqual("name-304", TestUtil.ToTestableString(obj[0].SpaceName), true);
                Assert.AreEqual("bc51034d-267d-4a39-a384-78196b0bc300", TestUtil.ToTestableString(obj[0].OrgGuid), true);
                Assert.AreEqual("bc51034d-267d-4a39-a384-78196b0bc300", TestUtil.ToTestableString(obj[0].BuildpackGuid), true);
                Assert.AreEqual("name-305", TestUtil.ToTestableString(obj[0].BuildpackName), true);
                Assert.AreEqual("STAGED", TestUtil.ToTestableString(obj[0].PackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].PreviousPackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].ParentAppGuid), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].ParentAppName), true);
                Assert.AreEqual("web", TestUtil.ToTestableString(obj[0].ProcessType), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].TaskName), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].TaskGuid), true);

            }
        }

    }
}